// <auto-generated />
using E_Commerce_App.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Commerce_App.Migrations
{
    [DbContext(typeof(E_CommerceDBContext))]
    [Migration("20230830082511_newSetupForDataBase")]
    partial class newSetupForDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Commerce_App.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Electric"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Houseware"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Food"
                        });
                });

            modelBuilder.Entity("E_Commerce_App.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            Name = "Screens"
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 1,
                            Name = "Fridges"
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 2,
                            Name = "Tables"
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 2,
                            Name = "Kitchen Tools"
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 3,
                            Name = "Meats"
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 3,
                            Name = "Food Stuff"
                        });
                });

            modelBuilder.Entity("E_Commerce_App.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            DepartmentID = 1,
                            Name = "Samsung",
                            Price = 350,
                            Quantity = 23
                        },
                        new
                        {
                            ID = 2,
                            DepartmentID = 1,
                            Name = "LG",
                            Price = 300,
                            Quantity = 40
                        },
                        new
                        {
                            ID = 3,
                            DepartmentID = 2,
                            Name = "Beko",
                            Price = 250,
                            Quantity = 50
                        },
                        new
                        {
                            ID = 4,
                            DepartmentID = 2,
                            Name = "Toshiba",
                            Price = 280,
                            Quantity = 40
                        },
                        new
                        {
                            ID = 5,
                            DepartmentID = 3,
                            Name = "4 Person lunch Table",
                            Price = 40,
                            Quantity = 100
                        },
                        new
                        {
                            ID = 6,
                            DepartmentID = 3,
                            Name = "8 Person lunch table",
                            Price = 70,
                            Quantity = 100
                        },
                        new
                        {
                            ID = 7,
                            DepartmentID = 4,
                            Name = "Teval Pan",
                            Price = 20,
                            Quantity = 45
                        },
                        new
                        {
                            ID = 8,
                            DepartmentID = 4,
                            Name = "Dishes",
                            Price = 15,
                            Quantity = 100
                        },
                        new
                        {
                            ID = 9,
                            DepartmentID = 5,
                            Name = "Sheep meat",
                            Price = 15,
                            Quantity = 110
                        },
                        new
                        {
                            ID = 10,
                            DepartmentID = 5,
                            Name = "Beef",
                            Price = 10,
                            Quantity = 80
                        },
                        new
                        {
                            ID = 11,
                            DepartmentID = 6,
                            Name = "Sunny frying oil",
                            Price = 10,
                            Quantity = 80
                        },
                        new
                        {
                            ID = 12,
                            DepartmentID = 6,
                            Name = "Durra Bean Box 500g",
                            Price = 1,
                            Quantity = 48
                        });
                });

            modelBuilder.Entity("E_Commerce_App.Models.Department", b =>
                {
                    b.HasOne("E_Commerce_App.Models.Category", "Category")
                        .WithMany("Departments")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("E_Commerce_App.Models.Product", b =>
                {
                    b.HasOne("E_Commerce_App.Models.Department", "Department")
                        .WithMany("Products")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("E_Commerce_App.Models.Category", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("E_Commerce_App.Models.Department", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
